{
 "title": "Modem (Details)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "mac_address", "label": "Modem MAC", "query": { "query": "label_values(mac_address)" } }
  ]
 },
 "panels": [
  {
   "title": "Vendor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "Model Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "MAC Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "CM IPv4 Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modem_info{mac_address=\"$mac_address\"}"
    }
   ]
  },
  {
   "title": "[Downstream] Channel Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "downstream_frequency{mac_address=\"$mac_address\"}",
     "legendFormat": "Channel ID: {{channel}}"
    }
   ]
  },
  {
   "title": "[Downstream] SNR by Channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "downstream_snr{mac_address=\"$mac_address\"}",
     "legendFormat": "Channel ID: {{channel}}"
    }
   ]
  },
  {
   "title": "[Downstream] Channel Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "downstream_power{mac_address=\"$mac_address\"}",
     "legendFormat": "Channel ID: {{channel}}"
    }
   ]
  },
  {
   "title": "[Upstream] Channel Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "upstream_frequency{mac_address=\"$mac_address\"}",
     "legendFormat": "Channel ID: {{channel}}"
    }
   ]
  },
  {
   "title": "[Upstream] Symbol Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Ksym/sec" } },
   "targets": [
    {
     "expr": "upstream_symbol_rate{mac_address=\"$mac_address\"}",
     "legendFormat": "Channel ID: {{channel}}"
    }
   ]
  },
  {
   "title": "[Upstream] Channel Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "upstream_power{mac_address=\"$mac_address\"}",
     "legendFormat": "Channel ID: {{channel}}"
    }
   ]
  }
 ]
}